### ISSUE TITLE
More details about sampling

### ISSUE THREAD

**Issue by gubertoli** [samedsaka/syntheticddos#2]
Dear @samedsaka , nice work!

Reading your paper, specifically, from section III-B, step 3, are you using 50% / 50% distribution (malign versus benign)? It was not possible to precisely infer from Figures 1-3.

Do you have implementation details about the original sampling you used for CIC-DDoS2019 ? (this is for using as baseline comparison)

**Comment by samedsaka** [comment]
Hi @gubertoli,

Sorry for the late response, and thank you for your interest.

Yes, you are correct. I used a 50/50 distribution between malicious and benign samples. However, since the CIC-DDoS2019 dataset has separate files for each type of DDoS attack, I sampled an equal number of DDoS and benign samples from each file. Specifically, I included all the benign samples from each file and selected the same number of DDoS samples from that file (as far as I remember, the number of benign samples was lower than malicious samples in each file). Therefore, the final dataset maintains a 50/50 distribution between DDoS and benign samples.

The following line of code performs this sampling:

```
    n_samples = df[' Label'].value_counts()['BENIGN']

    #for each file
    sampled_df = df.groupby(' Label', group_keys=False).apply(lambda x: x.sample(n=n_samples, random_state=1))

```

I hope the other steps are clear enough.

**Comment by gubertoli** [comment]
Thanks @samedsaka, all the best!
